### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by PatricYan**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)

### CODE REVIEW

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yanllearnn)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKupwY76yLKTdqH5c2p:-LKupwY76yLKTdqH5c2q:bkctfa7) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
> ```
> contract
> ```
first char should be upper case: Contract

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yanllearnn)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKupwY76yLKTdqH5c2p:-LKuq504D6kaEOGLOKfU:b-wm2rbv) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
> ```
> Hash Time Lock contract : htlc
> ```
Hash Time Lock Contract(HTLC) : HTLC

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yanllearnn)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqGLn2t5gK_kr45v6:-LKuqGLn2t5gK_kr45v7:brdor1j) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
> ```
> slices
> ```
what's this?
for Seele, only main chain and sub-chain.

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @yanllearnn)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqTiy6TG3nCk3bQIH:-LKuqTiy6TG3nCk3bQII:b-689tbl) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
> ```
> contracts
> ```
remove the suffix 's'
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqWL8AN9wt12IJmuQ:-LKuqWL8AN9wt12IJmuR:bq5jc69) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
> ```
> complete
> ```
completed

**Review by PatricYan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @WTer and @yanllearnn)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqGLn2t5gK_kr45v6:-LKuqcpq6feJJnWjEgDk:bjfchow) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> slices
> ```
what's this?
for Seele, only main chain and sub-chain.
</blockquote></details>

shard,slice is the shard,changed it to shard
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqWL8AN9wt12IJmuQ:-LKurA9h3LQi62P0Q0g-:bcmeuk1) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> complete
> ```
completed
</blockquote></details>

can not be full believed in Tom. changed
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKupwY76yLKTdqH5c2p:-LKurPKdBFzvHa3tBR8X:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Hash Time Lock contract : htlc
> ```
Hash Time Lock Contract(HTLC) : HTLC
</blockquote></details>

Done.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqTiy6TG3nCk3bQIH:-LKurQEz03ydwtBWI7La:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> contracts
> ```
remove the suffix 's'
</blockquote></details>

Done.

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @WTer)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqGLn2t5gK_kr45v6:-LKurpE0DxngFEDO8uz3:bd8hdkg) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, yanllearnn (pengfei Yan) wrote…</i></summary><blockquote>

shard,slice is the shard,changed it to shard
</blockquote></details>

here should be shards

**Review by PatricYan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: 0 of 1 files reviewed, all discussions resolved

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/seeleteam/labs/7#-LKuqGLn2t5gK_kr45v6:-LKus6Ju6-Hk7Tduqpra:b-enxkjx) ([raw file](https://github.com/seeleteam/labs/blob/128449f5fc275cbbc27f7b09efa1a98ea19e750d/README.md#L3)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

here should be shards
</blockquote></details>

it is shards.

**Review by WTer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7#-:-LKusF4cCagerv0Wt1FD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by WTer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
