### PR TITLE
modify the err message to uniformed format

### PR DESCRIPTION
**Pull request by PatricYan**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)

### CODE REVIEW

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yanllearnn)

___
*[swap/swap.go, line 96 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVT9BT3h0Ql4p7B4R7:-LKVT9BT3h0Ql4p7B4R8:brvar98) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L96)):*
> ```
> Failed json MarshalIndent
> ```
Failed to marshal tx

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 310 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTQJ2D2-StUuNzpwN:-LKVTQJ2D2-StUuNzpwO:b-tbd9ij) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L310)):*
> ```
> Failed secret-hex hash to bytes
> ```
Failed to convert secret-hex hash to bytes

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 364 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTdn11RfA72wGwJx5:-LKVTdn11RfA72wGwJx6:bwxuozi) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L364)):*
> ```
> Failed json unmarshal
> ```
Failed to unmarshal json

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 431 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVToteBe9GZ6ogAEmt:-LKVToteBe9GZ6ogAEmu:bxazamg) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L431)):*
> ```
> Failed your nonce is
> ```
Invalid nonce

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 467 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTxWIBrDJtKq6xDiF:-LKVTxWIBrDJtKq6xDiG:b-bqktuy) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L467)):*
> ```
> Failed 
> ```
remove it. 
"unsupported address type" is ok.

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 499 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVU4mf3F-OUN2gNqZf:-LKVU4mf3F-OUN2gNqZg:bjzo9a6) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L499)):*
> ```
> Failed contract address hex to byte
> ```
Failed to convert contract address hex to bytes

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @yanllearnn)

___
*[swap/swap.go, line 524 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVUAMF6h2-GMRavz41:-LKVUAMF6h2-GMRavz42:b3uihnk) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L524)):*
> ```
> Failed json MarshalIndent
> ```
Failed to marshal json
___
*[swap/swap.go, line 553 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVUMjW8PN59PzuQtuB:-LKVUMjW8PN59PzuQtuC:b-ar7j0d) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L553)):*
> ```
> Failed the value is not 32 bytes, len is: %d\n
> ```
The length %d is invalid, should be 32\n

**Review by PatricYan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @WTer)

___
*[swap/swap.go, line 96 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVT9BT3h0Ql4p7B4R7:-LKVbl637GesUKS9-wft:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L96)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed json MarshalIndent
> ```
Failed to marshal tx
</blockquote></details>

Done.
___
*[swap/swap.go, line 310 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTQJ2D2-StUuNzpwN:-LKVblhg1sBBREm6nqYD:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L310)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed secret-hex hash to bytes
> ```
Failed to convert secret-hex hash to bytes
</blockquote></details>

Done.
___
*[swap/swap.go, line 364 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTdn11RfA72wGwJx5:-LKVbmA29ZCh2SMPNtg7:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L364)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed json unmarshal
> ```
Failed to unmarshal json
</blockquote></details>

Done.
___
*[swap/swap.go, line 431 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVToteBe9GZ6ogAEmt:-LKVbmfY08lq3zhyOp6W:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L431)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed your nonce is
> ```
Invalid nonce
</blockquote></details>

Done.
___
*[swap/swap.go, line 467 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVTxWIBrDJtKq6xDiF:-LKVbiYD6kP_cWPZDjAB:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L467)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed 
> ```
remove it. 
"unsupported address type" is ok.
</blockquote></details>

Done.
___
*[swap/swap.go, line 499 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVU4mf3F-OUN2gNqZf:-LKVbj8S5Am5yaZSIRx8:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L499)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed contract address hex to byte
> ```
Failed to convert contract address hex to bytes
</blockquote></details>

Done.
___
*[swap/swap.go, line 524 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVUAMF6h2-GMRavz41:-LKVbjl33P6NvYNyK57T:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L524)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed json MarshalIndent
> ```
Failed to marshal json
</blockquote></details>

Done.
___
*[swap/swap.go, line 553 at r1](https://reviewable.io/reviews/seeleteam/labs/5#-LKVUMjW8PN59PzuQtuB:-LKVbkQ25ENK2oZlZyGr:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/f9114704b2c0a58758ad35d4e0c70883092ee004/swap/swap.go#L553)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> Failed the value is not 32 bytes, len is: %d\n
> ```
The length %d is invalid, should be 32\n
</blockquote></details>

Done.

**Review by WTer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/5#-:-LKVccX89Q8yQcKznzCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
