### PR TITLE
add getreceipt ,getbalance command

### PR DESCRIPTION
**Pull request by PatricYan**
This change is [Reviewable](https://reviewable.io/reviews/seeleteam/labs/6)

### CODE REVIEW

**Review by WTer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/6)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @yanllearnn)

___
*[swap/swap.go, line 311 at r1](https://reviewable.io/reviews/seeleteam/labs/6#-LKaHMCH0_-evR6mpMvv:-LKaHMCH0_-evR6mpMvw:b-pq5c4d) ([raw file](https://github.com/seeleteam/labs/blob/7b1f90202346528d39aca36db43d48d7b9b5180a/swap/swap.go#L311)):*
> ```
> getBalance
> ```
GetBalance

**Review by PatricYan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/6)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @WTer)

___
*[swap/swap.go, line 311 at r1](https://reviewable.io/reviews/seeleteam/labs/6#-LKaHMCH0_-evR6mpMvv:-LKaILyVEjfxjQlMaZLA:b-896fix) ([raw file](https://github.com/seeleteam/labs/blob/7b1f90202346528d39aca36db43d48d7b9b5180a/swap/swap.go#L311)):*
<details><summary><i>Previously, WTer (Wensi Liu) wrote…</i></summary><blockquote>

> ```
> getBalance
> ```
GetBalance
</blockquote></details>

Done.

**Review by WTer — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by WTer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/seeleteam/labs/6#-:-LKaJiQN4RcmqzEaLGi7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
